import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Des',
      email: 'admindes@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Sara',
      email: 'usersara@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Super Shirt',
      slug: 'super-shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      brand: 'Nike',
      price: 70,
      rating: 4.5,
      numReviews: 5,
      countInStock: 19,
      description: 'A modern shirt',
    },
    {
      name: 'Sport Shirt',
      slug: 'sport-shirt',
      category: 'Shirts',
      image: '/images/shirt2.jpg',
      brand: 'North Face',
      price: 80,
      rating: 3.5,
      numReviews: 15,
      countInStock: 20,
      description: 'A modern shirt',
    },
    {
      name: 'Fit Shirt',
      slug: 'fit-shirt',
      category: 'Shirts',
      image: '/images/shirt3.jpg',
      brand: 'Adidas',
      price: 85,
      rating: 3.5,
      numReviews: 15,
      countInStock: 20,
      description: 'A modern shirt',
    },
    {
      name: 'Super Pants',
      slug: 'super-pants',
      category: 'Pants',
      image: '/images/pants1.jpg',
      brand: 'Adidas',
      price: 90,
      rating: 2.5,
      numReviews: 25,
      countInStock: 10,
      description: 'Modern pants',
    },
    {
      name: 'Sport Pants',
      slug: 'sport-pants',
      category: 'Pants',
      image: '/images/pants2.jpg',
      brand: 'Nike',
      price: 100,
      rating: 4.5,
      numReviews: 22,
      countInStock: 13,
      description: 'Modern pants',
    },
    {
      name: 'Classic Pants',
      slug: 'classic-pants',
      category: 'Pants',
      image: '/images/pants3.jpg',
      brand: 'North Face',
      price: 120,
      rating: 4.3,
      numReviews: 29,
      countInStock: 14,
      description: 'Modern pants',
    },
  ],
};

export default data;
